version: '3.4'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - project
    volumes:
      - ./lib:/code/lib:ro
      - ./script:/code/script:ro
      - ./conf:/code/conf:ro

networks:
  project:
