---
swagger: '2.0'
schemes:
  - https

basePath: /api

info:
  version: 1.0.0
  title: Pointing

host: localhost:3000

consumes:
  - application/json

produces:
  - application/json

paths:
  /hello:
    get:
      x-mojo-name: hello
      x-mojo-to: 'hello#hello'
      summary: Hello
      description: Returns a hello
      produces:
        - application/json
      responses:
        '200':
          description: Hello
          schema:
            type: object
