#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;

BEGIN {
    unshift @INC, "$FindBin::Bin/../lib";
}

use Mojolicious::Commands;
use Devel::Cycle;

Mojolicious::Commands->start_app('Pointing');
